# Generated by Django 5.2.14 on 2026-05-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('data', 'Data'), ('design', 'Design'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('hr', 'HR'), ('legal', 'Legal'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('product', 'Product'), ('sales', 'Sales')], max_length=50),
        ),
    ]
