# Generated by Django 5.2.14 on 2026-05-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0002_employee_role_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
